# Generated by Django 4.2.7 on 2026-02-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', '👨 Male'), ('female', '👩 Female'), ('other', '🌟 Other'), ('prefer_not_to_say', '🔒 Prefer not to say')], default='prefer_not_to_say', help_text='Select your gender for personalized avatar', max_length=20),
        ),
    ]
